from enum import Enum

class TipoEstamento(str, Enum):
    ESTUDIANTE = "ESTUDIANTE"
    DOCENTE = "DOCENTE"
    ADMINISTRATIVO = "ADMINISTRATIVO"
    TRABAJADORES = "TRABAJADORES"
    PARTICULARES = "PARTICULARES"
