"""Add nombre to Baremo

Revision ID: 2be1383703c1
Revises: 6b1f672aa93c
Create Date: 2026-02-04 00:08:29.105226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be1383703c1'
down_revision: Union[str, Sequence[str], None] = '6b1f672aa93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baremo', sa.Column('nombre', sa.String(), server_default='Baremo General', nullable=False))
    op.alter_column('baremo', 'prueba_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baremo', 'prueba_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('baremo', 'nombre')
    # ### end Alembic commands ###