"""fix missing tables and fk consistency

Revision ID: 36e4910320f2
Revises: 4348c8a68b4b
Create Date: 2026-01-12 15:38:38.605072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e4910320f2'
down_revision: Union[str, Sequence[str], None] = '4348c8a68b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencia_estado'), 'competencia', ['estado'], unique=False)
    op.create_index(op.f('ix_competencia_external_id'), 'competencia', ['external_id'], unique=True)
    op.create_index(op.f('ix_competencia_fecha'), 'competencia', ['fecha'], unique=False)
    op.create_index(op.f('ix_competencia_id'), 'competencia', ['id'], unique=False)
    op.create_index(op.f('ix_competencia_nombre'), 'competencia', ['nombre'], unique=False)
    op.create_table('resultado_competencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('competencia_id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('prueba_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('posicion_final', sa.String(length=50), nullable=False),
    sa.Column('puesto_obtenido', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['competencia_id'], ['competencia.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prueba_id'], ['prueba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_competencia_external_id'), 'resultado_competencia', ['external_id'], unique=True)
    op.create_index(op.f('ix_resultado_competencia_id'), 'resultado_competencia', ['id'], unique=False)
    op.create_unique_constraint(None, 'entrenador', ['user_id'])
    op.drop_constraint(op.f('entrenador_user_id_fkey'), 'entrenador', type_='foreignkey')
    op.create_foreign_key(None, 'entrenador', 'users', ['user_id'], ['id'])
    op.add_column('historial_medico', sa.Column('atleta_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('historial_medico_auth_user_id_key'), 'historial_medico', type_='unique')
    op.create_unique_constraint(None, 'historial_medico', ['atleta_id'])
    op.drop_constraint(op.f('historial_medico_auth_user_id_fkey'), 'historial_medico', type_='foreignkey')
    op.create_foreign_key(None, 'historial_medico', 'atleta', ['atleta_id'], ['id'], ondelete='CASCADE')
    op.drop_column('historial_medico', 'auth_user_id')
    op.create_foreign_key(None, 'users', 'auth_users', ['auth_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('historial_medico', sa.Column('auth_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'historial_medico', type_='foreignkey')
    op.create_foreign_key(op.f('historial_medico_auth_user_id_fkey'), 'historial_medico', 'auth_users', ['auth_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'historial_medico', type_='unique')
    op.create_unique_constraint(op.f('historial_medico_auth_user_id_key'), 'historial_medico', ['auth_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('historial_medico', 'atleta_id')
    op.drop_constraint(None, 'entrenador', type_='foreignkey')
    op.create_foreign_key(op.f('entrenador_user_id_fkey'), 'entrenador', 'auth_users', ['user_id'], ['id'])
    op.drop_constraint(None, 'entrenador', type_='unique')
    op.drop_index(op.f('ix_resultado_competencia_id'), table_name='resultado_competencia')
    op.drop_index(op.f('ix_resultado_competencia_external_id'), table_name='resultado_competencia')
    op.drop_table('resultado_competencia')
    op.drop_index(op.f('ix_competencia_nombre'), table_name='competencia')
    op.drop_index(op.f('ix_competencia_id'), table_name='competencia')
    op.drop_index(op.f('ix_competencia_fecha'), table_name='competencia')
    op.drop_index(op.f('ix_competencia_external_id'), table_name='competencia')
    op.drop_index(op.f('ix_competencia_estado'), table_name='competencia')
    op.drop_table('competencia')
    # ### end Alembic commands ###