"""nuevos modelos

Revision ID: 4348c8a68b4b
Revises: 
Create Date: 2026-01-11 22:17:04.244199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4348c8a68b4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_is_active'), 'auth_users', ['is_active'], unique=False)
    op.create_table('baremo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('valor_baremo', sa.Float(), nullable=False),
    sa.Column('clasificacion', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baremo_external_id'), 'baremo', ['external_id'], unique=True)
    op.create_index(op.f('ix_baremo_id'), 'baremo', ['id'], unique=False)
    op.create_table('external_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('token_type', sa.Enum('AUTH_TOKEN', name='externalclasstokentype'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_type')
    )
    op.create_index(op.f('ix_external_tokens_id'), 'external_tokens', ['id'], unique=False)
    op.create_table('tipo_disciplina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_disciplina_external_id'), 'tipo_disciplina', ['external_id'], unique=True)
    op.create_index(op.f('ix_tipo_disciplina_id'), 'tipo_disciplina', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=17), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('tipo_identificacion', sa.Enum('PASAPORTE', 'CEDULA', 'RUC', name='tipoidentificacionenum'), nullable=False),
    sa.Column('identificacion', sa.String(), nullable=False),
    sa.Column('tipo_estamento', sa.Enum('ADMINISTRATIVOS', 'DOCENTES', 'ESTUDIANTES', 'TRABAJADORES', 'EXTERNOS', name='tipoestamentoenum'), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexoenum'), nullable=True),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'ATLETA', 'ENTRENADOR', 'REPRESENTANTE', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_index(op.f('ix_users_identificacion'), 'users', ['identificacion'], unique=True)
    op.create_table('auth_users_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_auth_users_sessions_external_id'), 'auth_users_sessions', ['external_id'], unique=True)
    op.create_index(op.f('ix_auth_users_sessions_id'), 'auth_users_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_sessions_refresh_token'), 'auth_users_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_auth_users_sessions_status'), 'auth_users_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_auth_users_sessions_user_id'), 'auth_users_sessions', ['user_id'], unique=False)
    op.create_table('entrenador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_pasante', sa.Boolean(), nullable=False),
    sa.Column('anios_experiencia', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=True),
    sa.Column('talla', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('alergias', sa.String(), nullable=True),
    sa.Column('enfermedades_hereditarias', sa.String(), nullable=True),
    sa.Column('enfermedades', sa.String(), nullable=True),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id')
    )
    op.create_index(op.f('ix_historial_medico_external_id'), 'historial_medico', ['external_id'], unique=True)
    op.create_index(op.f('ix_historial_medico_id'), 'historial_medico', ['id'], unique=False)
    op.create_table('prueba',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('siglas', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('tipo_prueba', sa.String(), nullable=False),
    sa.Column('unidad_medida', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('tipo_disciplina_id', sa.Integer(), nullable=False),
    sa.Column('baremo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['baremo_id'], ['baremo.id'], ),
    sa.ForeignKeyConstraint(['tipo_disciplina_id'], ['tipo_disciplina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prueba_external_id'), 'prueba', ['external_id'], unique=True)
    op.create_index(op.f('ix_prueba_id'), 'prueba', ['id'], unique=False)
    op.create_table('representante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_representante_id'), 'representante', ['id'], unique=False)
    op.create_table('atleta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Uuid(), nullable=False),
    sa.Column('anios_experiencia', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('representante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['representante_id'], ['representante.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_atleta_external_id'), 'atleta', ['external_id'], unique=True)
    op.create_table('entrenamiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('tipo_entrenamiento', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_entrenamiento', sa.Date(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrenamiento_external_id'), 'entrenamiento', ['external_id'], unique=True)
    op.create_index(op.f('ix_entrenamiento_id'), 'entrenamiento', ['id'], unique=False)
    op.create_table('registro_prueba_competencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('id_entrenador', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('prueba_id', sa.Integer(), nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['prueba_id'], ['prueba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_prueba_competencia_external_id'), 'registro_prueba_competencia', ['external_id'], unique=True)
    op.create_index(op.f('ix_registro_prueba_competencia_id'), 'registro_prueba_competencia', ['id'], unique=False)
    op.create_table('horario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('entrenamiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenamiento_id'], ['entrenamiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horario_external_id'), 'horario', ['external_id'], unique=True)
    op.create_index(op.f('ix_horario_id'), 'horario', ['id'], unique=False)
    op.create_table('registro_asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_asistencias_external_id'), 'registro_asistencias', ['external_id'], unique=True)
    op.create_index(op.f('ix_registro_asistencias_id'), 'registro_asistencias', ['id'], unique=False)
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=False),
    sa.Column('fecha_asistencia', sa.Date(), nullable=False),
    sa.Column('hora_llegada', sa.Time(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('registro_asistencias_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_asistencias_id'], ['registro_asistencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_external_id'), 'asistencia', ['external_id'], unique=True)
    op.create_index(op.f('ix_asistencia_id'), 'asistencia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencia_id'), table_name='asistencia')
    op.drop_index(op.f('ix_asistencia_external_id'), table_name='asistencia')
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_registro_asistencias_id'), table_name='registro_asistencias')
    op.drop_index(op.f('ix_registro_asistencias_external_id'), table_name='registro_asistencias')
    op.drop_table('registro_asistencias')
    op.drop_index(op.f('ix_horario_id'), table_name='horario')
    op.drop_index(op.f('ix_horario_external_id'), table_name='horario')
    op.drop_table('horario')
    op.drop_index(op.f('ix_registro_prueba_competencia_id'), table_name='registro_prueba_competencia')
    op.drop_index(op.f('ix_registro_prueba_competencia_external_id'), table_name='registro_prueba_competencia')
    op.drop_table('registro_prueba_competencia')
    op.drop_index(op.f('ix_entrenamiento_id'), table_name='entrenamiento')
    op.drop_index(op.f('ix_entrenamiento_external_id'), table_name='entrenamiento')
    op.drop_table('entrenamiento')
    op.drop_index(op.f('ix_atleta_external_id'), table_name='atleta')
    op.drop_table('atleta')
    op.drop_index(op.f('ix_representante_id'), table_name='representante')
    op.drop_table('representante')
    op.drop_index(op.f('ix_prueba_id'), table_name='prueba')
    op.drop_index(op.f('ix_prueba_external_id'), table_name='prueba')
    op.drop_table('prueba')
    op.drop_index(op.f('ix_historial_medico_id'), table_name='historial_medico')
    op.drop_index(op.f('ix_historial_medico_external_id'), table_name='historial_medico')
    op.drop_table('historial_medico')
    op.drop_table('entrenador')
    op.drop_index(op.f('ix_auth_users_sessions_user_id'), table_name='auth_users_sessions')
    op.drop_index(op.f('ix_auth_users_sessions_status'), table_name='auth_users_sessions')
    op.drop_index(op.f('ix_auth_users_sessions_refresh_token'), table_name='auth_users_sessions')
    op.drop_index(op.f('ix_auth_users_sessions_id'), table_name='auth_users_sessions')
    op.drop_index(op.f('ix_auth_users_sessions_external_id'), table_name='auth_users_sessions')
    op.drop_table('auth_users_sessions')
    op.drop_index(op.f('ix_users_identificacion'), table_name='users')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tipo_disciplina_id'), table_name='tipo_disciplina')
    op.drop_index(op.f('ix_tipo_disciplina_external_id'), table_name='tipo_disciplina')
    op.drop_table('tipo_disciplina')
    op.drop_index(op.f('ix_external_tokens_id'), table_name='external_tokens')
    op.drop_table('external_tokens')
    op.drop_index(op.f('ix_baremo_id'), table_name='baremo')
    op.drop_index(op.f('ix_baremo_external_id'), table_name='baremo')
    op.drop_table('baremo')
    op.drop_index(op.f('ix_auth_users_is_active'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###