"""fecha nacimiento nuleable

Revision ID: 4694d338b13c
Revises: 1202f6ae69d9
Create Date: 2026-01-06 22:29:02.840854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4694d338b13c'
down_revision: Union[str, Sequence[str], None] = '1202f6ae69d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atleta', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('historial_medico', 'auth_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'historial_medico', ['auth_user_id'])
    op.alter_column('registro_prueba_competencia', 'auth_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registro_prueba_competencia', 'auth_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'historial_medico', type_='unique')
    op.alter_column('historial_medico', 'auth_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('atleta', 'fecha_nacimiento',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###