"""Add marca range to Baremo

Revision ID: 46da3d3a523a
Revises: 2be1383703c1
Create Date: 2026-02-04 00:12:43.419747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46da3d3a523a'
down_revision: Union[str, Sequence[str], None] = '2be1383703c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baremo', sa.Column('marca_min_valida', sa.Float(), nullable=True))
    op.add_column('baremo', sa.Column('marca_max_valida', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baremo', 'marca_max_valida')
    op.drop_column('baremo', 'marca_min_valida')
    # ### end Alembic commands ###