"""Add resultado_entrenamiento model

Revision ID: 613ccae55690
Revises: 74c7f6e8eacc
Create Date: 2026-01-30 23:43:07.169216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '613ccae55690'
down_revision: Union[str, Sequence[str], None] = '74c7f6e8eacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_entrenamientos',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('external_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('entrenamiento_id', sa.Integer(), nullable=False),
        sa.Column('atleta_id', sa.Integer(), nullable=False),
        sa.Column('fecha', sa.Date(), nullable=False),
        sa.Column('distancia', sa.Float(), nullable=True),
        sa.Column('tiempo', sa.Float(), nullable=True),
        sa.Column('unidad_medida', sa.String(), nullable=True),
        sa.Column('evaluacion', sa.Integer(), nullable=True),
        sa.Column('observaciones', sa.String(), nullable=True),
        sa.Column('estado', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
        sa.ForeignKeyConstraint(['entrenamiento_id'], ['entrenamiento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_entrenamientos_external_id'), 'resultados_entrenamientos', ['external_id'], unique=True)
    op.create_index(op.f('ix_resultados_entrenamientos_id'), 'resultados_entrenamientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_entrenamientos_id'), table_name='resultados_entrenamientos')
    op.drop_index(op.f('ix_resultados_entrenamientos_external_id'), table_name='resultados_entrenamientos')
    op.drop_table('resultados_entrenamientos')
    # ### end Alembic commands ###