"""agregar_relacion_con_representante

Revision ID: 6783f4dcd9f7
Revises: af2652a51318
Create Date: 2026-01-04 20:33:16.340387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6783f4dcd9f7'
down_revision: Union[str, Sequence[str], None] = 'af2652a51318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atleta', sa.Column('representante_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atleta', 'representante', ['representante_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atleta', type_='foreignkey')
    op.drop_column('atleta', 'representante_id')
    # ### end Alembic commands ###