"""agregar campo name a horarios

Revision ID: 73e12d7d5be0
Revises: bdb782b9070a
Create Date: 2026-01-04 18:07:28.384724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e12d7d5be0'
down_revision: Union[str, Sequence[str], None] = 'bdb782b9070a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('atleta_representante_id_fkey'), 'atleta', type_='foreignkey')
    op.drop_column('atleta', 'representante_id')
    op.add_column('horario', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'name')
    op.add_column('atleta', sa.Column('representante_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('atleta_representante_id_fkey'), 'atleta', 'representante', ['representante_id'], ['id'])
    # ### end Alembic commands ###