"""Add emergency contact

Revision ID: 98794c6b1c28
Revises: 613ccae55690
Create Date: 2026-02-02 16:40:37.184784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98794c6b1c28'
down_revision: Union[str, Sequence[str], None] = '613ccae55690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.UUID(), nullable=True),
    sa.Column('talla', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('alergias', sa.String(), nullable=True),
    sa.Column('enfermedades_hereditarias', sa.String(), nullable=True),
    sa.Column('enfermedades', sa.String(), nullable=True),
    sa.Column('contacto_emergencia_nombre', sa.String(), nullable=True),
    sa.Column('contacto_emergencia_telefono', sa.String(), nullable=True),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id')
    )
    op.create_index(op.f('ix_historial_medico_external_id'), 'historial_medico', ['external_id'], unique=True)
    op.create_index(op.f('ix_historial_medico_id'), 'historial_medico', ['id'], unique=False)
    op.drop_index(op.f('ix_external_tokens_id'), table_name='external_tokens')
    op.drop_table('external_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_type', postgresql.ENUM('AUTH_TOKEN', name='externalclasstokentype'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('external_tokens_pkey')),
    sa.UniqueConstraint('token_type', name=op.f('external_tokens_token_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_external_tokens_id'), 'external_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_historial_medico_id'), table_name='historial_medico')
    op.drop_index(op.f('ix_historial_medico_external_id'), table_name='historial_medico')
    op.drop_table('historial_medico')
    # ### end Alembic commands ###