"""refactor_asistencia_enrollment

Revision ID: af2652a51318
Revises: 73e12d7d5be0
Create Date: 2026-01-04 18:58:30.180791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2652a51318'
down_revision: Union[str, Sequence[str], None] = '73e12d7d5be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia', sa.Column('registro_asistencias_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'asistencia', 'registro_asistencias', ['registro_asistencias_id'], ['id'])
    op.drop_constraint(op.f('registro_asistencias_asistencia_id_fkey'), 'registro_asistencias', type_='foreignkey')
    op.drop_column('registro_asistencias', 'asistencia_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro_asistencias', sa.Column('asistencia_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('registro_asistencias_asistencia_id_fkey'), 'registro_asistencias', 'asistencia', ['asistencia_id'], ['id'])
    op.drop_constraint(None, 'asistencia', type_='foreignkey')
    op.drop_column('asistencia', 'registro_asistencias_id')
    # ### end Alembic commands ###