"""agregal atributo para saber si el tleta asistir o no

Revision ID: bb5ca12861f4
Revises: dec9095123fa
Create Date: 2026-01-19 11:22:34.129924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5ca12861f4'
down_revision: Union[str, Sequence[str], None] = 'dec9095123fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia', sa.Column('atleta_confirmo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asistencia', 'atleta_confirmo')
    # ### end Alembic commands ###