"""create_resultados_pruebas_strict_final_v2

Revision ID: d01936e52e51
Revises: 3ae175afd3b8
Create Date: 2026-01-21 00:33:21.608245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01936e52e51'
down_revision: Union[str, Sequence[str], None] = '3ae175afd3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_pruebas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('prueba_id', sa.Integer(), nullable=False),
    sa.Column('baremo_id', sa.Integer(), nullable=False),
    sa.Column('marca_obtenida', sa.Float(), nullable=False),
    sa.Column('clasificacion_final', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['atleta.id'], ),
    sa.ForeignKeyConstraint(['baremo_id'], ['baremo.id'], ),
    sa.ForeignKeyConstraint(['prueba_id'], ['prueba.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_pruebas_external_id'), 'resultados_pruebas', ['external_id'], unique=True)
    op.create_index(op.f('ix_resultados_pruebas_id'), 'resultados_pruebas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_pruebas_id'), table_name='resultados_pruebas')
    op.drop_index(op.f('ix_resultados_pruebas_external_id'), table_name='resultados_pruebas')
    op.drop_table('resultados_pruebas')
    # ### end Alembic commands ###