"""agregal bool y fecha de confimacion a asistencia

Revision ID: dec9095123fa
Revises: 9c02ba0642b6
Create Date: 2026-01-19 08:02:47.114932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec9095123fa'
down_revision: Union[str, Sequence[str], None] = '9c02ba0642b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia', sa.Column('asistio', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('asistencia', sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asistencia', 'fecha_confirmacion')
    op.drop_column('asistencia', 'asistio')
    # ### end Alembic commands ###