"""Role como enum

Revision ID: f57340d194e3
Revises: 48bb4a3d59fa
Create Date: 2025-12-08 16:43:06.569312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57340d194e3'
down_revision: Union[str, Sequence[str], None] = '48bb4a3d59fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roleenum = sa.Enum('ADMINISTRADOR', 'ATLETA', 'ENTRENADOR', 'REPRESENTANTE', name='roleenum')
    roleenum.create(op.get_bind(), checkfirst=True)

    op.alter_column('auth_users', 'role', server_default=None)

    op.execute("""
    ALTER TABLE auth_users
    ALTER COLUMN role TYPE roleenum
    USING role::roleenum
    """)

    # Set default value
    op.execute("ALTER TABLE auth_users ALTER COLUMN role SET DEFAULT 'ATLETA'::roleenum")
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # Drop the enum default
    op.alter_column('auth_users', 'role', server_default=None)
    
    # Convert back to VARCHAR
    op.alter_column('auth_users', 'role',
               existing_type=sa.Enum('ADMINISTRADOR', 'ATLETA', 'ENTRENADOR', 'REPRESENTANTE', name='roleenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    # Re-add the VARCHAR default
    op.execute("ALTER TABLE auth_users ALTER COLUMN role SET DEFAULT 'ATLETA'::character varying")
    
    # Drop the ENUM type
    sa.Enum(name='roleenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###